// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNErzR7MnNsZzOce_dLb-tu_eXeNHWReU',
    appId: '1:689320295524:web:e2e2f9c2b84f6132633371',
    messagingSenderId: '689320295524',
    projectId: 'friendcircle-1a28a',
    authDomain: 'friendcircle-1a28a.firebaseapp.com',
    storageBucket: 'friendcircle-1a28a.appspot.com',
    measurementId: 'G-55SJRS7614',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAy-8AQW4exB9Tmjq0bLTJRNI6o4zW1maY',
    appId: '1:689320295524:android:e3b1dd2f5a96cc6b633371',
    messagingSenderId: '689320295524',
    projectId: 'friendcircle-1a28a',
    storageBucket: 'friendcircle-1a28a.appspot.com',
     measurementId: 'G-55SJRS7614',
    authDomain: 'friendcircle-1a28a.firebaseapp.com',

  );
}
